
services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_HOST=chromadb
    volumes:
      - chromadb_data:/chroma/.chroma

  agent-api:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    depends_on:
      - chromadb

  ui:
    build: ./ui
    command: uvicorn main:app --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    depends_on:
      - agent-api

volumes:
  chromadb_data: